### ISSUE TITLE
Cannot control climate device with umlaut in the name

### ISSUE THREAD

**Issue by syssi** [wmalgadey/tado_component#13]
I have a zone called "Küche" which cannot be controlled by tado_component. The climate component is unable to show the current temperature. If I change a setting (tempature, mode, etc.) the device doesn't receive the update.

![climate](https://cloud.githubusercontent.com/assets/2735933/24082603/95ba554c-0cc8-11e7-80eb-e09eb2aabf93.png)

**Comment by wmalgadey** [comment]
I will have to change a zone of mine to check this!

**Comment by wmalgadey** [comment]
I just tried it with a zone I renamed (Wohnzimmär). Everything worked fine!

I am trying to integrate this component into the main hass repository. Maybe this code is more robust. I created a branch in this repository with the same changes. Maybe try this one instead?

But you have to change the configuration (mainly remove `mytado_` suffix of username and password!).

**Comment by syssi** [comment]
Strange. :-) I will give it a try.

**Comment by wmalgadey** [comment]
Sadly I was not "allowed" to keep the change to the state (return the current temperature instead of the operation state). So there will be a problem in influxdb if you use it (because the unit and the state do not match!).

(maybe I will just change it here in the custom component and keep the "wrong" state in the main hass component)

**Comment by agross** [comment]
I had the same issue with `Küche`. Renaming to `Kitchen` worked.

**Comment by wmalgadey** [comment]
could you verify this problem with the official version? or with the version in this repository on the feature branch `feature/hass_migration`

**Comment by agross** [comment]
@wmalgadey I will, but there's another issue with the official version: https://github.com/home-assistant/home-assistant/issues/6845

**Comment by wmalgadey** [comment]
good to know! didn't see that :)

**Comment by agross** [comment]
I was unsure whether I should report issues here or there. I'll mention you in the future.

**Comment by wmalgadey** [comment]
The problem with the "umlaut" is, that I do not use the name of the zone anywhere! just the components have this name, and this is taken care of by hass itself (it "sanitizes" the entity names).

internally I just use the zone ids. I added a umlaut to one of my zones and it did work. Do you get any errors in the hass log?

**Comment by syssi** [comment]
I'm using the official version in HA 0.42 now. The issue seems to be gone.

**Comment by wmalgadey** [comment]
maybe @agross can check the wrong behavior on his side too?

**Comment by agross** [comment]
@wmalgadey I will, but I'm going on vacation tomorrow. I tried upgrading to HA 0.42.3 but still had problems turning climate off (manually, see related issue on HA repo that you fixed) - HTTP 422 Unprocessable entity showed up in the logs. I'm a bit in a hurry so I downgraded to 0.40, will report later.

**Comment by wmalgadey** [comment]
np! good vacation ;)
