### ISSUE TITLE
problems with tado_component

### ISSUE THREAD

**Issue by l00mi** [wmalgadey/tado_component#16]
hi, I experience problems with the tado client (the official merged one) do you see the same? The login does not work anymore for me.

**Comment by syssi** [comment]
If you use the official tado component of HA you must wait for one of the next minor releases. If you want to solve the problem quick and dirty you can edit the tado.py on your own:

The head of the file should look like this:

```"""
Support for the (unofficial) Tado api.
For more details about this component, please refer to the documentation at
https://home-assistant.io/components/tado/
"""
import logging
import urllib
from datetime import timedelta

import voluptuous as vol

from homeassistant.helpers.discovery import load_platform
from homeassistant.helpers import config_validation as cv
from homeassistant.const import CONF_USERNAME, CONF_PASSWORD
from homeassistant.util import Throttle

REQUIREMENTS = ['https://github.com/wmalgadey/PyTado/archive/'
                '0.1.10.zip#'
                'PyTado==0.1.10']
```
Replace the REQUIREMENTS by

```
REQUIREMENTS = ['https://github.com/wmalgadey/PyTado/archive/'
                '0.2.1.zip#'
                'PyTado==0.2.1']
```
and restart home assistant. The new PyTado library will be retrieved and used on the next startup.

**Comment by l00mi** [comment]
Nice! Thank you very much. I should have looked in the tado repo.
