### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by Filhgd** [wmalgadey/tado_component#18]
Hi all!

I've encountered this error today:

`Setup failed for tado_v1: Invalid config.`

**Comment by Filhgd** [comment]
Any news because it just stopped working here.

I get: `[homeassistant.setup] Setup failed for tado_v1: Component failed to initialize.`

and `ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform tado`

**Comment by wmalgadey** [comment]
what is your setup? which ha version are you using?
