### ISSUE TITLE
Merging to Home-Assistant Repo?

### ISSUE THREAD

**Issue by l00mi** [wmalgadey/tado_component#9]
The tado_component works for me quite well. I got 3 zones all showing up correctly. Do you plan to merge it into the main components repo?

**Comment by wmalgadey** [comment]
Why not! Is there a reference on how to do that?

**Comment by diplix** [comment]
https://home-assistant.io/developers/development_submitting/
https://home-assistant.io/developers/creating_components/

**Comment by wmalgadey** [comment]
Yes, that's what I did :)

But how to add it to the big repo?

**Comment by diplix** [comment]
sorry, i added a second link a minute later: https://home-assistant.io/developers/development_submitting/

**Comment by wmalgadey** [comment]
Ok! this will take some time to do all the needed tests and changes to the code style :)

**Comment by wmalgadey** [comment]
did a merge request https://github.com/home-assistant/home-assistant/pull/5952

**Comment by l00mi** [comment]
wow! this will take some time equals apparently to 3h :-) impressive!

**Comment by wmalgadey** [comment]
It was close to a day :)

Ps: I did some changes to the coding style some weeks ago, this helped alot ;)

**Comment by wmalgadey** [comment]
That's bad. They won't merge my component until I refactor my data handling. Currently I am using the sensors to store the data from mytado.com. They want me to store everything in climate device and create template sensors for special data needed.

**Comment by wmalgadey** [comment]
whoop whooop. It finaly seems to be in the right shape to get merged ;)

**Comment by l00mi** [comment]
I am following the PR. Genius, thank you for the great work!
